### ISSUE TITLE
Pokemon Master's

### ISSUE THREAD

**Issue by gudianirudha** [AM1CODES/Poke-Dex#279]
I thought of creating a new page for pokemon player's

**Comment by gudianirudha** [comment]
Example:
Name: Ash Ketchum
Gender: Male
Hometown: Pallet Town
Region: Kanto
List of Pokemons : 
Pikachu - Given. Not caught.
Caterpie - Caught. Released as a Butterfree.
Pidgeotto - Caught. Left in the wild as a Pidgeot
Bulbasaur - Caught.
Charmander - Caught. Joined Ash of his own will. Left to train. Rejoined and with Oak now.
Squirtle - Caught. Released back to the Squirtle Squad.
Krabby- Caught. With Prof. Oak as a Kingler
Raticate - Traded for Butterfree. Got back
Haunter - Joined Ash for fun. Left for Sabrina.
Primeape - Caught. Left for Fighting trainer.
Muk - Caught in the power plant.
Tauros - Caught in Safari Zone.
Lapras - Caught. Released with family.

**Comment by gudianirudha** [comment]
![TIPs3](https://user-images.githubusercontent.com/54411756/95646780-74502800-0ae9-11eb-953c-3938a9aee0ef.png)

**Comment by gudianirudha** [comment]
@AM1CODES

**Comment by AM1CODES** [comment]
We can actually add a page for pokemon masters. But including the pokemons that they have is not necessary but the other things like region and all, we can do it. I will  assign it to you if you  are interested in making it

**Comment by gudianirudha** [comment]
Yes I'm in

**Comment by AM1CODES** [comment]
Okay. So we need to make another page that contains the name of the Pokemon Trainers. Contents of the page will look similar to the pokemon pages, just like the cards, so that its easier for people add their pokemon masters as well. Everything remains same just inplace of pokemons we have Trainers. We also need to keep it as responsive as possible and we will have to add that section in our main page navbar as well. You can start working on it. Thank you!
